In [2]:
import tensorflow as tf

In [3]:
print (tf.__version__)

1.9.0


In [4]:
hello = tf.constant("Hello")

In [5]:
world = tf.constant("World")

In [6]:
type(hello)

tensorflow.python.framework.ops.Tensor

In [7]:
print (hello)

Tensor("Const:0", shape=(), dtype=string)


In [8]:
with tf.Session() as sess:
    result = sess.run(hello+world)

In [9]:
print(result)

b'HelloWorld'


In [14]:
const = tf.constant(10)

In [15]:
myzeros = tf.zeros((4,4))

In [16]:
Myones = tf.ones((2,2))

In [17]:
myrand = tf.random_normal((3,3),stddev = 2.0)

In [19]:
myranduni = tf.random_uniform((4,4), minval = 0, maxval = 1)

In [20]:
myrand


<tf.Tensor 'random_normal:0' shape=(3, 3) dtype=float32>

In [22]:
myList = [const, myzeros, myrand, myranduni, Myones]

In [23]:
sess = tf.InteractiveSession()

In [24]:
for item in myList:
    print (sess.run(item))
    print ('\n')

10


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


[[-2.6658037   2.211865    1.4769083 ]
 [-1.1004459  -0.19403975 -0.23422308]
 [ 4.098471   -0.52164626  1.639653  ]]


[[0.3920418  0.24271464 0.75754964 0.60086346]
 [0.50879467 0.3085699  0.01595008 0.0328238 ]
 [0.8042879  0.9216926  0.00595021 0.620075  ]
 [0.9435115  0.47770047 0.30720532 0.38770103]]


[[1. 1.]
 [1. 1.]]


